// src/compliance/report.ts — 合规体检报告 Markdown 渲染
//
// 把 ComplianceReport 渲染成红黄绿评分卡（可截图传播 = 月1 获客钩子）。
// 按法规分组，每项给状态图标 + 结论 + 整改建议。

import { REGULATION_NAMES } from './regulations.js'
import type { Regulation } from './regulations.js'
import type { ComplianceReport, ControlResult, ControlStatus } from './audit.js'
import type { ProjectScanResult, FindingKind } from './project-scan.js'
import { suggestDomestic } from '../rules/domestic-alternatives.js'

const STATUS_ICON: Record<ControlStatus, string> = {
  pass: '🟢',
  warn: '🟡',
  fail: '🔴',
  manual: '⚪',
}

const STATUS_TEXT_ZH: Record<ControlStatus, string> = {
  pass: '合规', warn: '部分', fail: '不合规', manual: '待确认',
}
const STATUS_TEXT_EN: Record<ControlStatus, string> = {
  pass: 'Pass', warn: 'Partial', fail: 'Fail', manual: 'Manual',
}

const REGULATION_ORDER: Regulation[] = ['CSL', 'PIPL', 'MLPS', 'CBDT', 'GENAI']

/** 渲染合规体检报告为 Markdown。locale 决定中英文。 */
export function renderComplianceReport(report: ComplianceReport, locale: 'zh' | 'en'): string {
  const zh = locale === 'zh'
  const L: string[] = []

  // ===== 标题 + 总评分卡 =====
  L.push(zh ? '# 🛡️ AI 应用合规体检报告' : '# 🛡️ AI Application Compliance Report')
  L.push('')
  L.push(zh
    ? `> ShellWard 合规网关自动生成 · ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC`
    : `> Generated by ShellWard Compliance Gateway · ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC`)
  L.push('')

  const bar = scoreBar(report.score)
  L.push(zh ? '## 总评' : '## Overall')
  L.push('')
  // 诚实原则：静态扫描下不报"优秀/A"式合规结论，以风险发现数为主指标
  if (report.staticScan) {
    const fn = report.failed + (report.projectPenalty ? 1 : 0)
    L.push(zh
      ? `**项目实测风险: ${report.failed === 0 && !report.projectPenalty ? '🟢 未发现可观测风险' : '🔴 发现风险，详见下方'}**`
      : `**Observable risk: ${report.failed === 0 && !report.projectPenalty ? '🟢 none found' : '🔴 see below'}**`)
    L.push('')
    L.push(`${bar}  ${report.score}/100 ${zh ? '（可观测合规项，仅供参考）' : '(observable controls only)'}`)
    void fn
  } else {
    L.push(`**${zh ? '合规得分' : 'Score'}: ${report.score}/100　${gradeBadge(report.grade)}**`)
    L.push('')
    L.push('```')
    L.push(`${bar}  ${report.score}/100  [${report.grade}]`)
    L.push('```')
  }
  L.push('')
  L.push(zh
    ? `🟢 合规 ${report.passed} ｜ 🟡 部分 ${report.warned} ｜ 🔴 不合规 ${report.failed} ｜ ⚪ 待核验 ${report.manual}　(共 ${report.total} 项)`
    : `🟢 Pass ${report.passed} ｜ 🟡 Partial ${report.warned} ｜ 🔴 Fail ${report.failed} ｜ ⚪ Review ${report.manual}　(${report.total} controls)`)
  if (report.projectPenalty && report.projectPenalty > 0) {
    L.push('')
    L.push(zh
      ? `> 含项目实测风险扣分 **-${report.projectPenalty}**（见下方「项目实测风险」）`
      : `> Includes **-${report.projectPenalty}** from project scan findings (see Project Scan Findings)`)
  }
  if (report.staticScan) {
    L.push('')
    L.push(zh
      ? `> ⚠ 本次为静态扫描：已检查 ${report.filesScanned ?? '?'} 个文件，仅评估可观测风险；**${report.manual} 项合规控制项未验证**（需部署 ShellWard 运行时或人工核验）。本报告不构成完整合规结论。`
      : `> ⚠ Static scan: ${report.filesScanned ?? '?'} files checked; **${report.manual} controls unverified**. Not a complete compliance verdict.`)
  }
  L.push('')

  // ===== 优先整改（fail 项，按严重度） =====
  const fails = report.results
    .filter(r => r.status === 'fail')
    .sort((a, b) => severityRank(b) - severityRank(a))
  if (fails.length > 0) {
    L.push(zh ? '## ⚠️ 优先整改项' : '## ⚠️ Priority Fixes')
    L.push('')
    for (const r of fails) {
      L.push(`- 🔴 **${zh ? r.control.title_zh : r.control.title_en}** `
        + `(${regName(r.control.regulation, zh)} ${r.control.article})`)
      L.push(`  - ${zh ? '整改' : 'Fix'}: ${zh ? r.control.remediation_zh : r.control.remediation_en}`)
    }
    L.push('')
  }

  // ===== 按法规分组明细 =====
  L.push(zh ? '## 分项明细' : '## Detailed Results')
  L.push('')

  const grouped = groupByRegulation(report.results)
  for (const reg of REGULATION_ORDER) {
    const items = grouped[reg]
    if (!items || items.length === 0) continue
    L.push(`### ${regName(reg, zh)}`)
    L.push('')
    L.push(zh
      ? '| 状态 | 控制项 | 条款 | 结论 |'
      : '| Status | Control | Article | Result |')
    L.push('|---|---|---|---|')
    for (const r of items) {
      const icon = STATUS_ICON[r.status]
      const txt = zh ? STATUS_TEXT_ZH[r.status] : STATUS_TEXT_EN[r.status]
      const title = zh ? r.control.title_zh : r.control.title_en
      const detail = (zh ? r.detail_zh : r.detail_en).replace(/\|/g, '/').replace(/\n/g, ' ')
      L.push(`| ${icon} ${txt} | ${title} | ${r.control.article} | ${detail} |`)
    }
    L.push('')
  }

  // ===== 免责声明 =====
  L.push('---')
  L.push(zh
    ? '> **说明**：本报告帮助评估并满足合规技术要求，不构成法律意见，亦不替代算法备案/定级备案/PIA 等主体责任。⚪ 待确认项需结合业务人工判定。'
    : '> **Note**: This report assists with technical compliance and is not legal advice. ⚪ items require manual review.')

  return L.join('\n')
}

const KIND_LABEL: Record<FindingKind, { zh: string; en: string; icon: string }> = {
  overseas: { zh: '数据出境风险', en: 'Data export risk', icon: '🌐' },
  secret: { zh: '硬编码密钥', en: 'Hardcoded secret', icon: '🔑' },
  pii: { zh: '个人信息暴露', en: 'PII exposure', icon: '🪪' },
  'env-perm': { zh: '.env 权限', en: '.env permission', icon: '📂' },
}
const KIND_ORDER: FindingKind[] = ['overseas', 'secret', 'pii', 'env-perm']

/**
 * 渲染「项目实测风险」段 —— 关于用户项目的真实发现 (文件:行)，
 * 这是评分卡可截图、可信的关键。附加在合规报告之后。
 */
export function renderProjectFindings(scan: ProjectScanResult, locale: 'zh' | 'en'): string {
  const zh = locale === 'zh'
  const L: string[] = []
  L.push(zh ? '## 🔍 项目实测风险' : '## 🔍 Project Scan Findings')
  L.push('')
  L.push(zh
    ? `> 已扫描 ${scan.filesScanned} 个文件${scan.truncated ? '（已达上限）' : ''} · 耗时 ${scan.durationMs ?? '?'}ms · 应用 ${scan.rulesChecked ?? '?'} 条检测规则`
    : `> Scanned ${scan.filesScanned} files${scan.truncated ? ' (limit reached)' : ''} · ${scan.durationMs ?? '?'}ms · ${scan.rulesChecked ?? '?'} detection rules`)
  L.push('')

  if (scan.findings.length === 0) {
    L.push(zh ? '🟢 未在项目文件中发现硬编码密钥、个人信息暴露或境外端点。' : '🟢 No hardcoded secrets, PII exposure, or overseas endpoints found in project files.')
    L.push('')
    return L.join('\n')
  }

  // 概览计数
  const counts = KIND_ORDER
    .filter(k => scan.counts[k] > 0)
    .map(k => `${KIND_LABEL[k].icon} ${zh ? KIND_LABEL[k].zh : KIND_LABEL[k].en}: ${scan.counts[k]}`)
    .join('　｜　')
  L.push(`**${counts}**`)
  L.push('')

  // 按类型分组列出（每类最多 15 条，避免报告过长）
  for (const kind of KIND_ORDER) {
    const items = scan.findings.filter(f => f.kind === kind)
    if (items.length === 0) continue
    const label = KIND_LABEL[kind]
    L.push(`### ${label.icon} ${zh ? label.zh : label.en} (${items.length})`)
    L.push('')
    for (const f of items.slice(0, 15)) {
      const loc = f.line ? `${f.file}:${f.line}` : f.file
      L.push(`- \`${loc}\` — ${f.detail}`)
    }
    if (items.length > 15) {
      L.push(zh ? `- …其余 ${items.length - 15} 项` : `- …and ${items.length - 15} more`)
    }
    L.push('')
  }

  // 处方：境内合规替代建议（仅当存在境外模型风险时）
  L.push(...renderDomesticGuidance(scan, locale))

  return L.join('\n')
}

/** 渲染「境内合规替代建议」—— 把数据出境风险变成可执行的迁移处方 */
function renderDomesticGuidance(scan: ProjectScanResult, locale: 'zh' | 'en'): string[] {
  const zh = locale === 'zh'
  const overseas = scan.findings.filter(f => f.kind === 'overseas')
  if (overseas.length === 0) return []

  // 去重境外厂商
  const seen = new Set<string>()
  const providers: { key: string; zh?: string; en?: string }[] = []
  for (const f of overseas) {
    const key = (f.endpointId || f.provider_en || f.provider_zh || '').toLowerCase()
    if (!key || seen.has(key)) continue
    seen.add(key)
    providers.push({ key: f.endpointId || f.provider_en || '', zh: f.provider_zh, en: f.provider_en })
  }

  const L: string[] = []
  L.push(zh ? '## ✅ 境内合规替代建议' : '## ✅ Domestic Compliance Alternatives')
  L.push('')
  L.push(zh
    ? '把数据出境风险变成可执行的迁移路径。境内主流模型多为 **OpenAI 兼容**接口：'
    : 'Turn data-export risk into a concrete migration path. Most domestic models are **OpenAI-compatible**:')
  L.push('')

  // 每个境外厂商的迁移难度
  for (const p of providers) {
    const s = suggestDomestic(p.key, p.zh, p.en)
    L.push(zh
      ? `- **${s.overseas_zh}** → 迁移难度: ${s.difficulty_zh}`
      : `- **${s.overseas_en}** → migration: ${s.difficulty_en}`)
  }
  L.push('')

  // 共享的境内候选表（取第一个建议的 alternatives，避免重复）
  const alts = suggestDomestic(providers[0].key, providers[0].zh, providers[0].en).alternatives
  L.push(zh ? '| 境内模型 | 厂商 | OpenAI 兼容 base_url |' : '| Domestic model | Vendor | OpenAI-compatible base_url |')
  L.push('|---|---|---|')
  for (const m of alts) {
    L.push(`| ${zh ? m.name_zh : m.name_en} | ${m.vendor_zh} | \`${m.baseUrl}\` |`)
  }
  L.push('')
  L.push(zh
    ? '> 对使用 `openai` SDK 的项目：通常仅需把 `base_url` 与 `api_key` 换成上表任一境内模型即可，业务代码无需改动。迁移前请以各厂商官方文档为准。'
    : '> For projects using the `openai` SDK: usually just swap `base_url` + `api_key` to a domestic model above — no business-code change. Verify against each vendor’s official docs first.')
  L.push('')
  return L
}

function scoreBar(score: number): string {
  const filled = Math.round(score / 5)
  return '█'.repeat(filled) + '░'.repeat(20 - filled)
}

function gradeBadge(grade: string): string {
  const map: Record<string, string> = {
    A: '🏆 优秀', B: '✅ 良好', C: '⚠️ 及格', D: '❌ 不及格',
  }
  return map[grade] || grade
}

function severityRank(r: ControlResult): number {
  return { critical: 4, high: 3, medium: 2, low: 1 }[r.control.severity]
}

function regName(reg: Regulation, zh: boolean): string {
  return zh ? REGULATION_NAMES[reg].zh : REGULATION_NAMES[reg].en
}

function groupByRegulation(results: ControlResult[]): Record<Regulation, ControlResult[]> {
  const out = {} as Record<Regulation, ControlResult[]>
  for (const r of results) {
    ;(out[r.control.regulation] ||= []).push(r)
  }
  return out
}
